apiVersion: v1
kind: Namespace
metadata:
  name: psa-privileged
  labels:
    owner: "psa-privileged"
    # PRIVILEGED: No restrictions (for system workloads)
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit-version: v1.29
    pod-security.kubernetes.io/warn-version: v1.29
  annotations:
    cks.exercise: "05-pod-security-admission"
    cks.level: "privileged"
    description: "System-level workloads (kube-system, monitoring)"
    psa.warning: "Only for trusted system workloads"
